#!/usr/bin/env bash

set -euo pipefail

ISSUE="${1:-}"
PLAN="${2:-}"
START_MARKER="<!-- agentic-template:implementation-plan:start -->"
END_MARKER="<!-- agentic-template:implementation-plan:end -->"

if [[ -z "$ISSUE" || -z "$PLAN" ]]; then
  echo "Usage: $0 <issue-number> <plan-path>"
  exit 1
fi

if [[ ! "$ISSUE" =~ ^[0-9]+$ ]]; then
  echo "Issue number must be numeric: $ISSUE"
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "Error: GitHub CLI 'gh' is not installed."
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "Error: GitHub CLI is not authenticated."
  echo "Run: gh auth login"
  exit 1
fi

if [[ ! -f "$PLAN" ]]; then
  echo "Plan not found: $PLAN"
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
PLAN_DIR="$(cd "$(dirname "$PLAN")" && pwd -P)"
PLAN_PATH="$PLAN_DIR/$(basename "$PLAN")"
EXPECTED_PREFIX="$REPO_ROOT/.agents/plans/${ISSUE}-"

if [[ "$PLAN_PATH" != "$EXPECTED_PREFIX"*.md ]]; then
  echo "Plan must match .agents/plans/${ISSUE}-*.md"
  echo "Received: $PLAN_PATH"
  exit 1
fi

PLAN_RELATIVE="${PLAN_PATH#"$REPO_ROOT"/}"
BODY="$(gh issue view "$ISSUE" --json body --jq '.body')"

PLAN_BLOCK="$START_MARKER
## Implementation plan

Detailed technical plan:

\`$PLAN_RELATIVE\`

Status: Ready for implementation
$END_MARKER"
export PLAN_BLOCK

marker_state="$(awk -v start="$START_MARKER" -v end="$END_MARKER" '
  $0 == start {
    if (state != 0) {
      invalid = 1
    }
    state = 1
    next
  }
  $0 == end {
    if (state != 1) {
      invalid = 1
    }
    state = 2
  }
  END {
    if (invalid || state == 1) {
      print "invalid"
    } else if (state == 2) {
      print "managed"
    } else {
      print "none"
    }
  }
' <<<"$BODY")"

if [[ "$marker_state" == "invalid" ]]; then
  echo "Error: issue body contains malformed implementation-plan markers."
  echo "Expected either zero markers or one matching marker pair."
  exit 1
fi

if [[ "$marker_state" == "managed" ]]; then
  UPDATED_BODY="$(awk \
    -v start="$START_MARKER" \
    -v end="$END_MARKER" '
      $0 == start { print ENVIRON["PLAN_BLOCK"]; inside = 1; next }
      inside && $0 == end { inside = 0; next }
      !inside { print }
    ' <<<"$BODY")"
elif [[ -z "$BODY" ]]; then
  UPDATED_BODY="$PLAN_BLOCK"
else
  # Replace blocks generated by older versions; otherwise append a managed block.
  UPDATED_BODY="$(awk '
    { lines[NR] = $0 }
    END {
      for (i = 1; i <= NR; i++) {
        legacy = (lines[i] == "## Implementation plan" && lines[i + 1] == "" && lines[i + 2] == "Detailed technical plan:" && lines[i + 3] == "" && lines[i + 4] ~ /^`[^`]+`$/ && lines[i + 5] == "" && lines[i + 6] == "Status: Ready for implementation")

        if (legacy) {
          if (!replaced) {
            print ENVIRON["PLAN_BLOCK"]
          }
          replaced = 1
          i += 6
          continue
        }

        print lines[i]
      }

      if (!replaced) {
        if (NR > 0 && lines[NR] != "") {
          print ""
        }
        print ENVIRON["PLAN_BLOCK"]
      }
    }
  ' <<<"$BODY")"
fi

if [[ "$UPDATED_BODY" == "$BODY" ]]; then
  echo "Issue #$ISSUE already references $PLAN_RELATIVE"
  exit 0
fi

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT
printf '%s\n' "$UPDATED_BODY" > "$TMP_FILE"

gh issue edit "$ISSUE" --body-file "$TMP_FILE"

echo "Issue #$ISSUE updated with plan: $PLAN_RELATIVE"
